name = "diary-web"

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "diary-db"
database_id = "d06caa21-556e-477f-bf86-959dd894e047"

# KV namespace for session storage (optional)
[[kv_namespaces]]
binding = "SESSIONS"
id = "df5ca1583e2645328dda4d28cab3fcca"
preview_id = "your-preview-kv-namespace-id-here"

[vars]
ENVIRONMENT = "production"
