name = "diary-app"

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "diary-db"
database_id = "bf6cb2c5-4ae1-4451-bff9-890295639e98"

# KV namespace for session storage (optional)
[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id-here"
preview_id = "your-preview-kv-namespace-id-here"

[vars]
ENVIRONMENT = "production"
